/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package s18ejercicio01;

/**
 *
 * @author alumno
 */
public class AppEjemplo extends javax.swing.JFrame {

    /**
     * Creates new form AppEjemplo
     */
    public AppEjemplo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblPractica01 = new javax.swing.JLabel();
        lblExamenParcial = new javax.swing.JLabel();
        lblPractica02 = new javax.swing.JLabel();
        lblExamenFinal = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        txtPractica01 = new javax.swing.JTextField();
        txtExamenParcial = new javax.swing.JTextField();
        txtPractica02 = new javax.swing.JTextField();
        txtExamenFinal = new javax.swing.JTextField();
        lblNotaFinal = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitulo.setText("Calcular Notas");

        lblPractica01.setText("Practica 01");

        lblExamenParcial.setText("Examen Parcial");

        lblPractica02.setText("Practica 02");

        lblExamenFinal.setText("Examen Final");

        btnCalcular.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        txtPractica02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPractica02ActionPerformed(evt);
            }
        });

        txtExamenFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExamenFinalActionPerformed(evt);
            }
        });

        lblNotaFinal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNotaFinal.setText("Nota Final:");

        lblResultado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblResultado.setText("Resultado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTitulo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPractica01)
                                            .addComponent(lblExamenParcial)
                                            .addComponent(lblPractica02)
                                            .addComponent(lblExamenFinal))
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtPractica02, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                            .addComponent(txtExamenParcial, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPractica01, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtExamenFinal)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblResultado)
                                    .addComponent(lblNotaFinal))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPractica01)
                    .addComponent(txtPractica01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblExamenParcial)
                    .addComponent(txtExamenParcial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPractica02)
                    .addComponent(txtPractica02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExamenFinal)
                    .addComponent(txtExamenFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNotaFinal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblResultado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPractica02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPractica02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPractica02ActionPerformed

    private void txtExamenFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExamenFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExamenFinalActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        
        // Definiendo Variables
        double p1, p2, sumap1p2;
        double pp, ep, ef;
        double notaFinal;
        
        // Adquirir P1        
        p1 = Double.parseDouble(txtPractica01.getText());
        // Adquirir P2
        p2 = Double.parseDouble(txtPractica02.getText());
        // Adquirir EP
        ep = Double.parseDouble(txtExamenParcial.getText());
        // Adquirir EF
        ef = Double.parseDouble(txtExamenFinal.getText());
        // Sumar P1 + P2
        sumap1p2 = p1 + p2;
        // Divir SumaP1P2 / 2
        pp = sumap1p2 / 2;
        // Sumar PP + EP + EF
        notaFinal = (pp + ep + ef) / 3;
        // Mostrar Nota Final
        lblNotaFinal.setText("Nota Final: " + notaFinal);
        // Mostrar Resultado
        if (notaFinal >= 13 ) {
            lblResultado.setText("Resultado: APROBADO");
        }
        else {
            lblResultado.setText("Resultado: DESAPROBADO");
        }        
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppEjemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppEjemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppEjemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppEjemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppEjemplo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel lblExamenFinal;
    private javax.swing.JLabel lblExamenParcial;
    private javax.swing.JLabel lblNotaFinal;
    private javax.swing.JLabel lblPractica01;
    private javax.swing.JLabel lblPractica02;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtExamenFinal;
    private javax.swing.JTextField txtExamenParcial;
    private javax.swing.JTextField txtPractica01;
    private javax.swing.JTextField txtPractica02;
    // End of variables declaration//GEN-END:variables
}
